package desktopApplication;

import java.awt.Color;
import java.awt.Dimension;

import java.awt.Font;

//import java.awt.GridBagConstraints;
//import java.awt.GridBagLayout;
//import java.awt.GridLayout;
//import java.awt.Insets;
import java.awt.Rectangle;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
//import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;

//import oracle.jdeveloper.layout.PaneConstraints;
//import oracle.jdeveloper.layout.PaneLayout;
//import oracle.jdeveloper.layout.XYConstraints;
//import oracle.jdeveloper.layout.XYLayout;

public class RegisterForm extends JFrame {
    private JPanel jPanel1 = new JPanel();
    private JPanel jPanel2 = new JPanel();
    private JSeparator jSeparator1 = new JSeparator();
    private JPanel jPanel3 = new JPanel();
    private JLabel jLabel1 = new JLabel();
    private JLabel jLabel2 = new JLabel();
    private JLabel jLabel3 = new JLabel();
    private JScrollPane jScrollPane1 = new JScrollPane();
    private JLabel jLabel4 = new JLabel();
    private JTextField jTextField1 = new JTextField();
    private JButton jButton1 = new JButton();
    private JPasswordField jPasswordField1 = new JPasswordField();
    private JLabel jLabel5 = new JLabel();
    private JPasswordField jPasswordField2 = new JPasswordField();
    private JLabel jLabel6 = new JLabel();
    private JRadioButton jRadioButton1 = new JRadioButton();
    private JRadioButton jRadioButton2 = new JRadioButton();
    private JLabel jLabel7 = new JLabel();
    private JLabel jLabel8 = new JLabel();
    private JTextField jTextField2 = new JTextField();
    private JLabel jLabel9 = new JLabel();
    private JTextField jTextField3 = new JTextField();
    private JLabel jLabel10 = new JLabel();
    private JTextField jTextField4 = new JTextField();
    private JLabel jLabel11 = new JLabel();
    private JTextField jTextField5 = new JTextField();
    private JLabel jLabel12 = new JLabel();
    private JList jList1 = new JList();
    private JList jList2 = new JList();
    private JButton jButton2 = new JButton();
    private JButton jButton3 = new JButton();
    private JButton jButton4 = new JButton();
    private JCheckBox jCheckBox1 = new JCheckBox();
    private JButton jButton5 = new JButton();
    private JLabel jLabel13 = new JLabel();
    private ButtonGroup bg=new ButtonGroup();

    public RegisterForm() {
        try {
            jbInit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jbInit() throws Exception {
        this.getContentPane().setLayout( null );
        this.setSize(new Dimension(1024, 760));
        this.setTitle("Registration form");
        this.setVisible(true);
        this.setResizable(false);
        this.setFont(new Font("Dialog", 1, 12));
        this.setForeground(new Color(255, 165, 165));
        this.setBackground(Color.white);
        this.setBounds(new Rectangle(10, 10, 1024, 760));
        jPanel1.setBounds(new Rectangle(0, 0, 1010, 115));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.black, 2));
        jPanel1.setBackground(new Color(255, 208, 170));
        jPanel1.setSize(new Dimension(1006, 115));
        jPanel1.setLayout(null);
        jPanel2.setBounds(new Rectangle(0, 125, 1005, 30));
        jPanel2.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel2.setLayout(null);
        jSeparator1.setBounds(new Rectangle(3, 120, 1000, 2));
        jSeparator1.setSize(new Dimension(1000, 2));
        jPanel3.setBounds(new Rectangle(102, 150, 815, 560));
        jPanel3.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED));
        jPanel3.setLayout(null);
        jPanel3.setBackground(Color.white);
        jLabel1.setText("Registration form");
        jLabel1.setBounds(new Rectangle(10, 15, 215, 30));
        jLabel1.setFont(new Font("Verdana", 0, 24));
        jLabel1.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jLabel2.setText("Login Info");
        jLabel2.setBounds(new Rectangle(295, 50, 205, 30));
        jLabel2.setFont(new Font("Trebuchet MS", 1, 15));
        jLabel2.setHorizontalTextPosition(SwingConstants.LEFT);
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("User Id :");
        jLabel3.setBounds(new Rectangle(10, 100, 140, 25));
        jLabel3.setFont(new Font("Tahoma", 1, 12));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jScrollPane1.setBounds(new Rectangle(955, 165, 35, 580));
        jLabel4.setText("Password :");
        jLabel4.setBounds(new Rectangle(10, 145, 140, 25));
        jLabel4.setFont(new Font("Tahoma", 1, 12));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jTextField1.setBounds(new Rectangle(185, 100, 260, 25));
        jButton1.setText("Check Availability");
        jButton1.setBounds(new Rectangle(465, 100, 115, 20));
        jButton1.setFont(new Font("Tahoma", 0, 10));
        jPasswordField1.setBounds(new Rectangle(185, 140, 260, 25));
        jLabel5.setText("Confirm Password :");
        jLabel5.setBounds(new Rectangle(15, 185, 135, 25));
        jLabel5.setFont(new Font("Tahoma", 1, 12));
        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jPasswordField2.setBounds(new Rectangle(185, 180, 260, 25));
        jLabel6.setText("Type of User :");
        jLabel6.setBounds(new Rectangle(20, 225, 135, 25));
        jLabel6.setFont(new Font("Tahoma", 1, 12));
        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jRadioButton1.setText("Individual");
        jRadioButton1.setBounds(new Rectangle(185, 220, 115, 25));
        jRadioButton1.setBackground(Color.white);
        jRadioButton2.setText("Corporate");
        jRadioButton2.setBounds(new Rectangle(310, 220, 115, 25));
        jRadioButton2.setBackground(Color.white);
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        jLabel7.setText("Personal Info");
        jLabel7.setBounds(new Rectangle(285, 255, 205, 30));
        jLabel7.setFont(new Font("Trebuchet MS", 1, 15));
        jLabel7.setHorizontalTextPosition(SwingConstants.LEFT);
        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setText("Name :");
        jLabel8.setBounds(new Rectangle(5, 295, 140, 25));
        jLabel8.setFont(new Font("Tahoma", 1, 12));
        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jTextField2.setBounds(new Rectangle(185, 290, 265, 25));
        jLabel9.setText("Ph/mobile no :");
        jLabel9.setBounds(new Rectangle(15, 335, 135, 25));
        jLabel9.setFont(new Font("Tahoma", 1, 12));
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jTextField3.setBounds(new Rectangle(185, 330, 265, 25));
        jLabel10.setText("Address Line 1 :");
        jLabel10.setBounds(new Rectangle(20, 375, 125, 25));
        jLabel10.setFont(new Font("Tahoma", 1, 12));
        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jTextField4.setBounds(new Rectangle(185, 370, 265, 25));
        jLabel11.setText("Address Line 2 :");
        jLabel11.setBounds(new Rectangle(20, 415, 125, 25));
        jLabel11.setFont(new Font("Tahoma", 1, 12));
        jLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        jTextField5.setBounds(new Rectangle(185, 410, 265, 25));
        jLabel12.setText("City :");
        jLabel12.setBounds(new Rectangle(25, 445, 115, 30));
        jLabel12.setFont(new Font("Tahoma", 1, 12));
        jLabel12.setHorizontalAlignment(SwingConstants.CENTER);
        jList1.setBounds(new Rectangle(185, 450, 265, 25));
        jList1.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED));
        jList2.setBounds(new Rectangle(330, 515, 0, 0));
        jButton2.setText("BACK");
        jButton2.setBounds(new Rectangle(385, 520, 120, 30));
        jButton2.setFont(new Font("Tahoma", 1, 12));
        jButton3.setText("RESET");
        jButton3.setBounds(new Rectangle(240, 520, 120, 30));
        jButton3.setFont(new Font("Tahoma", 1, 12));
        jButton4.setText("SUBMIT");
        jButton4.setBounds(new Rectangle(100, 520, 120, 30));
        jButton4.setFont(new Font("Tahoma", 1, 12));
        jCheckBox1.setText("I Agree");
        jCheckBox1.setBounds(new Rectangle(320, 490, 125, 20));
        jCheckBox1.setBackground(Color.white);
        jCheckBox1.setFont(new Font("Tahoma", 0, 10));
        jButton5.setText("Terms and Conditions");
        jButton5.setBounds(new Rectangle(190, 485, 115, 30));
        jButton5.setFont(new Font("Tahoma", 0, 9));
        jButton5.setBackground(Color.white);
        jButton5.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jLabel13.setText("Welcome to the Pizza World!!!");
        jLabel13.setBounds(new Rectangle(20, 25, 960, 60));
        jLabel13.setFont(new Font("Tahoma", 1, 60));
        this.getContentPane().add(jSeparator1, null);
        this.getContentPane().add(jPanel2, null);
        jPanel1.add(jLabel13, null);
        this.getContentPane().add(jPanel1, null);
        this.getContentPane().add(jPanel3, null);
        jPanel3.add(jButton5, null);
        jPanel3.add(jCheckBox1, null);
        jPanel3.add(jButton4, null);
        jPanel3.add(jButton3, null);
        jPanel3.add(jButton2, null);
        jPanel3.add(jList2, null);
        jPanel3.add(jList1, null);
        jPanel3.add(jLabel12, null);
        jPanel3.add(jTextField5, null);
        jPanel3.add(jLabel11, null);
        jPanel3.add(jTextField4, null);
        jPanel3.add(jLabel10, null);
        jPanel3.add(jTextField3, null);
        jPanel3.add(jLabel9, null);
        jPanel3.add(jTextField2, null);
        jPanel3.add(jLabel8, null);
        jPanel3.add(jLabel7, null);
        jPanel3.add(jRadioButton2, null);
        jPanel3.add(jRadioButton1, null);
        jPanel3.add(jLabel6, null);
        jPanel3.add(jPasswordField2, null);
        jPanel3.add(jLabel5, null);
        jPanel3.add(jPasswordField1, null);
        jPanel3.add(jButton1, null);
        jPanel3.add(jTextField1, null);
        jPanel3.add(jLabel4, null);
        jPanel3.add(jScrollPane1, null);
        jPanel3.add(jLabel3, null);
        jPanel3.add(jLabel2, null);
        jPanel3.add(jLabel1, null);
    }
    public static void main (String args[]) {
        RegisterForm register=new RegisterForm();
    }
}
